#A user create a reservation
POST {{api_endpoint}}/reservations
Content-Type: application/json
Authorization: bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQxNzM3MTE5ODUzYzUyOTI3NjUyZTMiLCJlbWFpbCI6InRoYW9AZ21haWwuY29tIiwicGFzc3dvcmQiOiIiLCJyZXNlcnZhdGlvbiI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMTAtMzFUMjE6MzY6NDkuNDc1WiIsInVwZGF0ZWRBdCI6IjIwMjMtMTEtMDFUMTU6NTQ6NTAuNzcwWiIsIl9fdiI6MCwicmVzZXJ2YXRpb25zIjpbeyJyZXN0YXVyYW50Ijp7Im5hbWUiOiJTdHJpbmciLCJpbWFnZSI6IlN0cmluZyJ9LCJudW1iZXJPZlBlb3BsZSI6NSwiZGF0ZSI6IjIwMjMtMTItMDFUMDg6MTM6NTcuNDU4WiIsInN0YXR1cyI6Ik5ldyIsIl9pZCI6IjY1NDI3NGFiMTNmMjFhMDA2Zjc5NTEyNCIsImNyZWF0ZWRBdCI6IjIwMjMtMTEtMDFUMTU6NTQ6MTkuNDc1WiIsInVwZGF0ZWRBdCI6IjIwMjMtMTEtMDFUMTU6NTQ6MTkuNDc1WiJ9LHsicmVzdGF1cmFudCI6eyJuYW1lIjoiU3RyaW5nIiwiaW1hZ2UiOiJTdHJpbmcifSwibnVtYmVyT2ZQZW9wbGUiOjUsImRhdGUiOiIyMDIzLTEyLTAxVDA4OjEzOjU3LjQ1OFoiLCJzdGF0dXMiOiJOZXciLCJfaWQiOiI2NTQyNzRjYTEzZjIxYTAwNmY3OTUxMjYiLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAxVDE1OjU0OjUwLjc3MFoiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAxVDE1OjU0OjUwLjc3MFoifV0sImlhdCI6MTY5ODg1NDEzNn0.vtpwPLMZ77zmx1DFKgepbx6dMeorflyR-wNR5nztQwM

{
  "userId": "6541737119853c52927652e3",
  "restaurant": {
    "name": "String",
    "image": "String"
  },
  "numberOfPeople": 5,
  "date": "2023-11-31T08:13:57.458Z"
}

###
#Load all reservations of a user
GET {{api_endpoint}}/reservations/user/6541737119853c52927652e3
Content-Type: application/json
Authorization: bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQxNzM3MTE5ODUzYzUyOTI3NjUyZTMiLCJlbWFpbCI6InRoYW9AZ21haWwuY29tIiwicGFzc3dvcmQiOiIiLCJyZXNlcnZhdGlvbiI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMTAtMzFUMjE6MzY6NDkuNDc1WiIsInVwZGF0ZWRBdCI6IjIwMjMtMTEtMDFUMTU6NTQ6NTAuNzcwWiIsIl9fdiI6MCwicmVzZXJ2YXRpb25zIjpbeyJyZXN0YXVyYW50Ijp7Im5hbWUiOiJTdHJpbmciLCJpbWFnZSI6IlN0cmluZyJ9LCJudW1iZXJPZlBlb3BsZSI6NSwiZGF0ZSI6IjIwMjMtMTItMDFUMDg6MTM6NTcuNDU4WiIsInN0YXR1cyI6Ik5ldyIsIl9pZCI6IjY1NDI3NGFiMTNmMjFhMDA2Zjc5NTEyNCIsImNyZWF0ZWRBdCI6IjIwMjMtMTEtMDFUMTU6NTQ6MTkuNDc1WiIsInVwZGF0ZWRBdCI6IjIwMjMtMTEtMDFUMTU6NTQ6MTkuNDc1WiJ9LHsicmVzdGF1cmFudCI6eyJuYW1lIjoiU3RyaW5nIiwiaW1hZ2UiOiJTdHJpbmcifSwibnVtYmVyT2ZQZW9wbGUiOjUsImRhdGUiOiIyMDIzLTEyLTAxVDA4OjEzOjU3LjQ1OFoiLCJzdGF0dXMiOiJOZXciLCJfaWQiOiI2NTQyNzRjYTEzZjIxYTAwNmY3OTUxMjYiLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAxVDE1OjU0OjUwLjc3MFoiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAxVDE1OjU0OjUwLjc3MFoifV0sImlhdCI6MTY5ODg1NDEzNn0.vtpwPLMZ77zmx1DFKgepbx6dMeorflyR-wNR5nztQwM

###
#Update a reservation
PATCH {{api_endpoint}}/reservations/654274ab13f21a006f795124
Content-Type: application/json
Authorization: bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQxNzM3MTE5ODUzYzUyOTI3NjUyZTMiLCJlbWFpbCI6InRoYW9AZ21haWwuY29tIiwicGFzc3dvcmQiOiIiLCJyZXNlcnZhdGlvbiI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMTAtMzFUMjE6MzY6NDkuNDc1WiIsInVwZGF0ZWRBdCI6IjIwMjMtMTEtMDFUMTU6NTQ6NTAuNzcwWiIsIl9fdiI6MCwicmVzZXJ2YXRpb25zIjpbeyJyZXN0YXVyYW50Ijp7Im5hbWUiOiJTdHJpbmciLCJpbWFnZSI6IlN0cmluZyJ9LCJudW1iZXJPZlBlb3BsZSI6NSwiZGF0ZSI6IjIwMjMtMTItMDFUMDg6MTM6NTcuNDU4WiIsInN0YXR1cyI6Ik5ldyIsIl9pZCI6IjY1NDI3NGFiMTNmMjFhMDA2Zjc5NTEyNCIsImNyZWF0ZWRBdCI6IjIwMjMtMTEtMDFUMTU6NTQ6MTkuNDc1WiIsInVwZGF0ZWRBdCI6IjIwMjMtMTEtMDFUMTU6NTQ6MTkuNDc1WiJ9LHsicmVzdGF1cmFudCI6eyJuYW1lIjoiU3RyaW5nIiwiaW1hZ2UiOiJTdHJpbmcifSwibnVtYmVyT2ZQZW9wbGUiOjUsImRhdGUiOiIyMDIzLTEyLTAxVDA4OjEzOjU3LjQ1OFoiLCJzdGF0dXMiOiJOZXciLCJfaWQiOiI2NTQyNzRjYTEzZjIxYTAwNmY3OTUxMjYiLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAxVDE1OjU0OjUwLjc3MFoiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAxVDE1OjU0OjUwLjc3MFoifV0sImlhdCI6MTY5ODg1NDEzNn0.vtpwPLMZ77zmx1DFKgepbx6dMeorflyR-wNR5nztQwM

{
  "numberOfPeople": 10,
  "status": "Done"
}