#Get categories
GET {{api_endpoint}}/categories?withRestaurant=true

###
#Get restaurant by category Id
GET {{api_endpoint}}/categories/655b67e3a84041916ba8786c/restaurants


###
#Get top 5 restaurants
GET {{api_endpoint}}/categories/restaurants?numOfTop=5

###
#Get top 5 restaurants
GET {{api_endpoint}}/categories/restaurants


###
#Get all restaurants
GET {{api_endpoint}}/categories/restaurants?isTrending=true


###
#Get images of a restaurant
GET {{api_endpoint}}/categories/64a01af9372d0c7ce7802f5c/restaurants/655b5fa8902f499aca317112/images