#Set favourite restaurant
PATCH {{api_endpoint}}/categories/64ad0f459d460b89d0c425db/restaurants/64ad0f459d460b89d0c425dc?isFavourite=true
Content-Type: application/json
Authorization: bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQxNzM3MTE5ODUzYzUyOTI3NjUyZTMiLCJlbWFpbCI6InRoYW9AZ21haWwuY29tIiwicGFzc3dvcmQiOiIiLCJyZXNlcnZhdGlvbiI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMTAtMzFUMjE6MzY6NDkuNDc1WiIsInVwZGF0ZWRBdCI6IjIwMjMtMTAtMzFUMjE6MzY6NDkuNDc1WiIsIl9fdiI6MCwiaWF0IjoxNjk4ODUxNjQ3fQ.bY-RVotmukWq5R0PMJFOQjSotAP9p3MkOJlpWDwZSjY


###
#Set favourite dishes
PATCH {{api_endpoint}}/categories/64a01af9372d0c7ce7802f5c/restaurants/64a01af9372d0c7ce7802f5d/dishes/64a01af9372d0c7ce7802f5e

