#Get all categories
POST {{api_endpoint}}/categories/
Content-Type: application/json
Authorization: bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTViNjY4ZTU5MDA1MDc5MzliZTBmOTUiLCJlbWFpbCI6InRoYW9AZ21haWwuY29tIiwicGFzc3dvcmQiOiIiLCJmYXZvdXJpdGVSZXN0YXVyYW50cyI6W10sImZhdm91cml0ZURpc2hlcyI6W10sInJlc2VydmF0aW9ucyI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMTEtMjBUMTQ6MDA6NDYuNTA1WiIsInVwZGF0ZWRBdCI6IjIwMjMtMTEtMjBUMTQ6MDA6NDYuNTA1WiIsIl9fdiI6MCwiaWF0IjoxNzAwNDg4OTU2fQ.GAhY8WqZlEy0B96KSkh6Q7GtVTYTpDebnkHWR1rN0KY

{
    "name": "Vietnam",
    "restaurants": [
    ]
}

###
#Add a restaurant to a category
POST {{api_endpoint}}/categories/655b67f0a84041916ba87870/restaurants
Content-Type: application/json
Authorization: bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTViNjY4ZTU5MDA1MDc5MzliZTBmOTUiLCJlbWFpbCI6InRoYW9AZ21haWwuY29tIiwicGFzc3dvcmQiOiIiLCJmYXZvdXJpdGVSZXN0YXVyYW50cyI6W10sImZhdm91cml0ZURpc2hlcyI6W10sInJlc2VydmF0aW9ucyI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMTEtMjBUMTQ6MDA6NDYuNTA1WiIsInVwZGF0ZWRBdCI6IjIwMjMtMTEtMjBUMTQ6MDA6NDYuNTA1WiIsIl9fdiI6MCwiaWF0IjoxNzAwNDg4OTU2fQ.GAhY8WqZlEy0B96KSkh6Q7GtVTYTpDebnkHWR1rN0KY

{
  "name": "Sandwich Slinger",
  "address": "1867 Lee Avenue, Lawrence, KS",
  "services": [
    "WIFI"
  ,"PARKING"
  ,"BAR"
  ,"WALK"
  ],
  "isTrending": true,
  "rate": 5.0,
  "distance": 6.5,
  "longDescription": "The regional cuisine of different regions of the Alps is called Alpine cuisine",
  "shortDescription": "Despite clear regional differences, this cuisine has been characterised throughout the entire Alpine region for centuries by the isolated rural life",
  "timeOpen": "07:00 - 22: 00",
  "dayOfWeek": "Monday to Sunday",
  "image": "https://images.pexels.com/photos/3252051/pexels-photo-3252051.jpeg?auto=compress",
  "imageList": [
    "https://images.pexels.com/photos/3252051/pexels-photo-3252051.jpeg?auto=compress",
    "https://images.pexels.com/photos/5786388/pexels-photo-5786388.jpeg?auto=compress",
    "https://images.pexels.com/photos/8753546/pexels-photo-8753546.jpeg?auto=compress",
    "https://images.pexels.com/photos/7195551/pexels-photo-7195551.jpeg?auto=compress",
    "https://images.pexels.com/photos/14017650/pexels-photo-14017650.jpeg?auto=compress",
    "https://images.pexels.com/photos/14736914/pexels-photo-14736914.jpeg?auto=compress",
    "https://images.pexels.com/photos/7582942/pexels-photo-7582942.jpeg?auto=compress",
    "https://images.pexels.com/photos/1378424/pexels-photo-1378424.jpeg?auto=compress",
    "https://images.pexels.com/photos/1581554/pexels-photo-1581554.jpeg?auto=compress",
    "https://images.pexels.com/photos/279768/pexels-photo-279768.jpeg?auto=compress"
  ],
  "dishes": [
    {
      "name": "Freshly Squeezed Orange Juice",
      "description": "Montagu's great-great-great-great-great-great grandson, Orlando Montagu, founded a chain called Earl of Sandwich",
      "rate": 4,
      "price": 15.9
    ,"image": "https://images.pexels.com/photos/338713/pexels-photo-338713.jpeg?auto=compress"

    },
    {
      "name": "Detox Water with Cucumber and Mint",
      "description": "Montagu's great-great-great-great-great-great grandson, Orlando Montagu, founded a chain called Earl of Sandwich",
      "rate": 5,
      "price": 20,
      "image": "https://images.pexels.com/photos/1484678/pexels-photo-1484678.jpeg?auto=compress"
    }
  ]
}

###
# "image": "https://s3.us-west-2.amazonaws.com/images.unsplash.com/application-1688213434869-d9e3e4ed414dimage",
# image": "https://s3.us-west-2.amazonaws.com/images.unsplash.com/application-1689068026691-d32ca47ba741image",

###
#Add a dish to a restaurant
POST {{api_endpoint}}/categories/64ad211acde3b553079129f1/restaurants/64ad21a3cde3b553079129ff/dishes
Content-Type: application/json
Authorization: bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTViNjY4ZTU5MDA1MDc5MzliZTBmOTUiLCJlbWFpbCI6InRoYW9AZ21haWwuY29tIiwicGFzc3dvcmQiOiIiLCJmYXZvdXJpdGVSZXN0YXVyYW50cyI6W10sImZhdm91cml0ZURpc2hlcyI6W10sInJlc2VydmF0aW9ucyI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMTEtMjBUMTQ6MDA6NDYuNTA1WiIsInVwZGF0ZWRBdCI6IjIwMjMtMTEtMjBUMTQ6MDA6NDYuNTA1WiIsIl9fdiI6MCwiaWF0IjoxNzAwNDg4OTU2fQ.GAhY8WqZlEy0B96KSkh6Q7GtVTYTpDebnkHWR1rN0KY

{
  "name": "Waldorf Salad",
  "description": "Montagu's great-great-great-great-great-great grandson, Orlando Montagu, founded a chain called Earl of Sandwich",
  "rate": 3,
  "price": 12.9,
  "image": "https://s3.us-west-2.amazonaws.com/images.unsplash.com/application-1688214208977-31253dc508dfimage"
}
###