#Get all categories
POST {{api_endpoint}}/categories/
Content-Type: application/json
Authorization: bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTVhYmVlNDJkYzcxY2JmOTk0M2ZmYTgiLCJlbWFpbCI6InRoYW9AZ21haWwuY29tIiwicGFzc3dvcmQiOiIiLCJmYXZvdXJpdGVSZXN0YXVyYW50cyI6W10sImZhdm91cml0ZURpc2hlcyI6W10sInJlc2VydmF0aW9ucyI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMTEtMjBUMDI6MDU6MjQuMTEwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMTEtMjBUMDI6MDU6MjQuMTEwWiIsIl9fdiI6MCwiaWF0IjoxNzAwNDg2MjE2fQ.q-AwUOJUsvcH53tLaLYQO80L0DhoSJ4oYzc80AM1Ka4

{
    "name": "France",
    "restaurants": [
    ]
}

###
#Add a restaurant to a category
POST {{api_endpoint}}/categories/64a01af9372d0c7ce7802f5c/restaurants
Content-Type: application/json
Authorization: bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTVhYmVlNDJkYzcxY2JmOTk0M2ZmYTgiLCJlbWFpbCI6InRoYW9AZ21haWwuY29tIiwicGFzc3dvcmQiOiIiLCJmYXZvdXJpdGVSZXN0YXVyYW50cyI6W10sImZhdm91cml0ZURpc2hlcyI6W10sInJlc2VydmF0aW9ucyI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMTEtMjBUMDI6MDU6MjQuMTEwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMTEtMjBUMDI6MDU6MjQuMTEwWiIsIl9fdiI6MCwiaWF0IjoxNzAwNDg2MjE2fQ.q-AwUOJUsvcH53tLaLYQO80L0DhoSJ4oYzc80AM1Ka4

{
  "name": "El Paso Tex Mex Bar and Grill",
  "address": "53 E Broadway Ave, Fairfield, IA 52556",
  "services": [
    "WIFI"
  ,"PARKING"
  ,"BAR"
  ,"WALK"
  ],
  "isTrending": true,
  "rate": 5.0,
  "distance": 6.5,
  "longDescription": "The regional cuisine of different regions of the Alps is called Alpine cuisine",
  "shortDescription": "Despite clear regional differences, this cuisine has been characterised throughout the entire Alpine region for centuries by the isolated rural life",
  "timeOpen": "07:00 - 22: 00",
  "dayOfWeek": "Monday to Sunday",
  "image": "https://s3.us-west-2.amazonaws.com/images.unsplash.com/application-1689068039307-3004b72c6608image",
  "imageList": [
    "https://images.pexels.com/photos/67468/pexels-photo-67468.jpeg?auto=compress",
    "https://images.pexels.com/photos/2102037/pexels-photo-2102037.jpeg?auto=compress"
  ],
  "dishes": [
    {
      "name": "Sandwich",
      "description": "Montagu's great-great-great-great-great-great grandson, Orlando Montagu, founded a chain called Earl of Sandwich",
      "rate": 4,
      "price": 15.9
    ,"image": "https://s3.us-west-2.amazonaws.com/images.unsplash.com/application-1688214208977-31253dc508dfimage"

    },
    {
      "name": "Waldorf Salad",
      "description": "Montagu's great-great-great-great-great-great grandson, Orlando Montagu, founded a chain called Earl of Sandwich",
      "rate": 3,
      "price": 12.9,
      "image": "https://s3.us-west-2.amazonaws.com/images.unsplash.com/application-1688214162400-2fd90334dc87image"
    }
  ]
}

###
# "image": "https://s3.us-west-2.amazonaws.com/images.unsplash.com/application-1688213434869-d9e3e4ed414dimage",
# image": "https://s3.us-west-2.amazonaws.com/images.unsplash.com/application-1689068026691-d32ca47ba741image",

###
#Add a dish to a restaurant
POST {{api_endpoint}}/categories/64ad211acde3b553079129f1/restaurants/64ad21a3cde3b553079129ff/dishes
Content-Type: application/json
Authorization: bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTVhYmVlNDJkYzcxY2JmOTk0M2ZmYTgiLCJlbWFpbCI6InRoYW9AZ21haWwuY29tIiwicGFzc3dvcmQiOiIiLCJmYXZvdXJpdGVSZXN0YXVyYW50cyI6W10sImZhdm91cml0ZURpc2hlcyI6W10sInJlc2VydmF0aW9ucyI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMTEtMjBUMDI6MDU6MjQuMTEwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMTEtMjBUMDI6MDU6MjQuMTEwWiIsIl9fdiI6MCwiaWF0IjoxNzAwNDg2MjE2fQ.q-AwUOJUsvcH53tLaLYQO80L0DhoSJ4oYzc80AM1Ka4

{
  "name": "Waldorf Salad",
  "description": "Montagu's great-great-great-great-great-great grandson, Orlando Montagu, founded a chain called Earl of Sandwich",
  "rate": 3,
  "price": 12.9,
  "image": "https://s3.us-west-2.amazonaws.com/images.unsplash.com/application-1688214208977-31253dc508dfimage"
}
###
#"image": "https://s3.us-west-2.amazonaws.com/images.unsplash.com/application-1688214162400-2fd90334dc87image"
#"image": "https://s3.us-west-2.amazonaws.com/images.unsplash.com/application-1688214208977-31253dc508dfimage"